# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('zipcode', models.IntegerField()),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('phone1Type', models.CharField(max_length=8)),
                ('phone2Type', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('newCustomer', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultMilestones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'DefaultMilestones',
            },
        ),
        migrations.CreateModel(
            name='DefaultTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('purchase', models.NullBooleanField()),
                ('locality', models.CharField(max_length=128)),
                ('brokerage', models.CharField(max_length=128)),
                ('tag1', models.CharField(max_length=128)),
                ('tag2', models.CharField(max_length=128)),
                ('tag3', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('wbs', models.IntegerField()),
                ('prerequisites', models.NullBooleanField()),
                ('dependents', models.NullBooleanField()),
                ('milestone', models.CharField(max_length=128)),
                ('milestoneDate', models.DateTimeField()),
                ('beforeAfter', models.NullBooleanField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.Client')),
            ],
            options={
                'verbose_name_plural': 'DefaultTasks',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=128)),
                ('scheduled', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brokerage', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('zipcode', models.IntegerField()),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('phone1Type', models.CharField(max_length=8)),
                ('phone2Type', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('wbs', models.IntegerField()),
                ('prerequisites', models.NullBooleanField()),
                ('ripeDate', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('status', models.CharField(max_length=8)),
                ('dependents', models.NullBooleanField()),
                ('milestone', models.CharField(default='None', max_length=128)),
                ('beforeAfter', models.NullBooleanField()),
                ('overDue', models.NullBooleanField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.Client')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(max_length=20)),
                ('property', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=8)),
                ('active', models.BooleanField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('lastActivity', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.Client')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.Realtor')),
            ],
            options={
                'ordering': ['startDate'],
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.Transactions'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.Transactions'),
        ),
        migrations.AddField(
            model_name='activity',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.Client'),
        ),
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.Tasks'),
        ),
    ]
