# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezclose', '0003_auto_20181022_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
