# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezclose', '0005_auto_20181026_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezclose.Brokerage'),
        ),
        migrations.AddField(
            model_name='property',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone1Type',
            field=models.CharField(blank=True, choices=[('CELL', 'cell'), ('OFFICE', 'office'), ('HOME', 'home'), ('ADMIN', 'admin')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone2Type',
            field=models.CharField(blank=True, choices=[('CELL', 'cell'), ('OFFICE', 'office'), ('HOME', 'home'), ('ADMIN', 'admin')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone1Type',
            field=models.CharField(blank=True, choices=[('CELL', 'cell'), ('OFFICE', 'office'), ('HOME', 'home'), ('ADMIN', 'admin')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone2Type',
            field=models.CharField(blank=True, choices=[('CELL', 'cell'), ('OFFICE', 'office'), ('HOME', 'home'), ('ADMIN', 'admin')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transactionType',
            field=models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell'), ('SELL_BUY', 'sell / buy')], max_length=20),
        ),
    ]
