# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezclose', '0007_auto_20181027_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='type',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('DOCUMENTS', 'Documents'), ('ADMIN', 'Administrative')], max_length=128),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('SFH', 'Single Family Home'), ('TOWNHOME', 'Townhouse'), ('CONDO', 'Condominium'), ('DUPLEX', 'Duplex')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.CharField(blank=True, choices=[('MEETING', 'Meeting'), ('RESEARCH', 'Research'), ('DOCUMENTS', 'Documents'), ('ADMIN', 'Administrative'), ('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('INFO_REVIEW', 'Information Review'), ('VENDOR', 'Vendor Action')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(blank=True, choices=[('NOT_READY', 'Not Ready'), ('READY', 'Ready'), ('DUE_ON', 'Due On'), ('DUE', 'Due'), ('OVERDUE', 'Overdue'), ('CRITICAL', 'Critical'), ('STARTED', 'Started'), ('COMPLETE', 'Complete')], max_length=10, null=True),
        ),
    ]
