# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezclose', '0008_auto_20181027_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(blank=True, null=True)),
                ('dateChanged', models.DateTimeField(blank=True, null=True)),
                ('modified', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.Client')),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REALTOR', 'Realtor'), ('REAL_ESTATE_BROKER', 'Real Estate Broker'), ('LENDER', 'Lender'), ('MORTGAGE_BROKER', 'Mortgage Broker'), ('BANKER', 'Banker'), ('CLOSING', 'Closing'), ('ATTORNEY', 'Attorney'), ('INSURANCE', 'Home Owners Insurance'), ('INSPECTOR', 'Home Inspector'), ('SPECIALTY_INSPECTOR', 'Speialty Inspector'), ('HOME_REPAIR', 'Home Repair'), ('CONTRACTOR', 'Contractor'), ('WARRANTY', 'Home Warranty'), ('OTHER', 'Other')], max_length=25)),
                ('Company', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=128, null=True)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('manager', models.CharField(blank=True, max_length=128, null=True)),
                ('mngrphone', models.CharField(blank=True, max_length=20, null=True)),
                ('mngremail', models.EmailField(blank=True, max_length=254, null=True)),
                ('locality', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezclose.TeamMember')),
            ],
            options={
                'verbose_name_plural': 'TeamMembers',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.TeamMember'),
        ),
        migrations.AddField(
            model_name='team',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezclose.Transactions'),
        ),
    ]
