# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-04 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezclose', '0009_auto_20181027_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttasks',
            name='purchase',
            field=models.CharField(blank=True, choices=[('BUY', 'buy'), ('SELL', 'sell'), ('SELL_BUY', 'sell / buy')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('ACTIVE', 'Active'), ('COMPLETE', 'Complete'), ('INACTIVE', 'Inactive'), ('ABANDONED', 'Abandoned')], max_length=10),
        ),
    ]
