# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-23 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezclose', '0013_auto_20181222_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamtype',
            options={'verbose_name_plural': 'TeamTypes'},
        ),
    ]
