# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-23 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezclose', '0014_auto_20181223_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='Company',
            new_name='company',
        ),
    ]
