# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-23 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezclose', '0016_auto_20181223_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamtype',
            old_name='ttype',
            new_name='type',
        ),
    ]
