# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-05 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezclose', '0018_auto_20181225_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='myRealtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezclose.Realtor'),
        ),
    ]
